dockitems_remove:
- Launchpad
- TV
- Podcasts
- 'App Store'

dockitems_persist:
- name: "Visual Studio Code"
  path: "/Applications/Visual Studio Code.app/"
  pos: 1

ansible_python_interpreter: /opt/homebrew/bin/python3