#SPDX-License-Identifier: MIT-0
---
- name: Clone dotfiles
  git:
    repo: "{{ remote_repo }}"
    dest: "{{ local_repo }}"
    #version: "{{ version }}"
  become: false

- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  with_items: "{{ directories }}"

- name: Link dotfiles
  file:
    src: "{{ local_repo }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    mode: 0600
  become: false
  with_items: "{{ links }}"