#SPDX-License-Identifier: MIT-0
---
- name: Tap repositories
  community.general.homebrew_tap:
    name: "{{ item }}"
  loop: "{{ brew_taps }}"

- name: Install brew formulas
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_formulas }}"

- name: Install brew casks
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_casks }}"

- community.general.mas:
    id: "{{ item }}"
    state: present
  become: false
  loop: "{{ mas_apps }}"
